### ISSUE TITLE
Test scripts for generate plots.

### ISSUE THREAD

**Issue by pavel-collab** [Exactlywb/grasshopper_riscv#13]
In my opinion, it will be a good idea to write some scripts, that will automat run programs, save data and produce plots to compare implementation. Acceleration and efficiency for example. Anyway, we will need plots for article and by using scripts we will be able to produce more results for same time.

I think, we should to assign this task to someone.

**Comment by Exactlywb** [comment]
Closed with https://github.com/Exactlywb/grasshopper_riscv/commit/db5367e823baccbe52bbea1b6eefe0610dd4b468
