### ISSUE TITLE
[BUG]: Tricky output 

### ISSUE THREAD

**Issue by kolobabka** [Exactlywb/grasshopper_riscv#20]
Aflter execution (both simple and vectorized versions) we get tricky symbols in stdin stream 
The result of my experiments: 
```
vb-sc:/media/vb-sc/new_space/grasshopper_riscv$ ./build/bin/simple testsuite/1.test generation/key
---
...
---
Running 4793/4797 block: usy in the pit; 
Running 4794/4797 block: perhaps it requi
Running 4795/4797 block: red a dozen --wh
Running 4796/4797 block: o shall tell?"

vb-sc:/media/vb-sc/new_space/grasshopper_riscv$ 65;1;9c
```
What the symbols are **65;1;9c**? Need to investigate with it

**Comment by Exactlywb** [comment]
I'll take a look

**Comment by Exactlywb** [comment]
It looks like "^@" in vim is '\0' so no reason to fix it and everything works correct.
