### ISSUE TITLE
a script for collecting the results 

### ISSUE THREAD

**Issue by kolobabka** [Exactlywb/grasshopper_riscv#24]
@pavel-collab 
We need to collect results in special way. There are some stages I had when collected first results:
* build the project
* get objdump files of simple and vectorized elfs
* get start and final addresses of "interesting" functions (which are provided in results)
* launch simple and vectorized with the `Spike` simulator with `-g` option (collection of PCs histogram)
* calculate the number of executed "interesting" PCs 
* build a graph 

The approximate example:

```
$ cmake --build build 
$ riscv64-unknown-elf-objdump -d build/bin/simple > sim_dis
$ riscv64-unknown-elf-objdump -d build/bin/vectorized > vec_dis
$ spike -g --isa=rv64gcv pk ./build/bin/simple testsuite/1.test generation/key >& sim_stat
$ spike -g --isa=rv64gcv pk ./build/bin/vectorized testsuite/1.test generation/key >& vec_stat
$ ./script < sim_stat
apply_ls : 5286741780
$ ./script < vec_stat 
apply_ls : 534964122
```

The example of my naive script: 

```cpp
#include <vector>
#include <iostream>
#include <utility>
#include <algorithm>

int main() {
    std::vector<std::pair<size_t, size_t>> vec;
    unsigned num;
    std::cin >> num;
    
    size_t start, fin;
    std::cin >> std::hex >> start >> std::hex >> fin;

    for (int i = 0; i < num; ++i) {
        size_t tmp_1, tmp_2;
        std::cin >> std::hex >> tmp_1 >> tmp_2;

        if (tmp_1 >= start && tmp_1 <= fin) {
            vec.emplace_back(tmp_1, tmp_2);
        }
    } 

    size_t res = 0;
    for (auto &&pair) {
        res += pair.second;
    }
    std::cout << "res : " << res << std::endl;
}
```

**Comment by Exactlywb** [comment]
I want to mention that we should monitor the instruction number of non-vectorized functions and the whole program too. This way we are able to understand that vectorization doesn't worse the other functions

**Comment by Exactlywb** [comment]
Related with https://github.com/Exactlywb/grasshopper_riscv/issues/8

**Comment by Exactlywb** [comment]
Closed with https://github.com/Exactlywb/grasshopper_riscv/commit/db5367e823baccbe52bbea1b6eefe0610dd4b468
