### ISSUE TITLE
Pregenerate all tables

### ISSUE THREAD

**Issue by Exactlywb** [Exactlywb/grasshopper_riscv#3]
At the moment we generate Muls, Coefs and LS_tbl using the next part of code:
```
void grasshoper_encrypt(Block *block, Key *key)
{
  //TODO: remove it with autogenerating for tables
  static int generate = 1;
  if (generate)
  {
    generate_mul_tbl ();
    generate_coef_tbl ();
    generate_LS_tbl ();
    generate = 0;
  }
```

As I understand all these 3 tables may be pregenerate before the whole program.  We should do it and save it instead of S, invS and lin tables (see config.h).

@Krym4s @kolobabka, am I right or these tables can't be pregenerated as I thought?

**Comment by Exactlywb** [comment]
Maybe @pavel-collab...

**Comment by Exactlywb** [comment]
@pavel-collab is volunteer.

**Comment by pavel-collab** [comment]
I need to check source code this week before solve the problem. Will do it this week. As I understood only possible way to generate random bytes array during the build step is to use a META programming. One possible option, that I have found for now is https://clck.ru/366Vk9 But it need to use boost lib.

**Comment by Exactlywb** [comment]
Here is no any reason to use meta programming (also we use C language)

This issue is not about random array generating (moreover this problem can't be solved using meta programming at all). Here we have the problem that we generate the SAME tables every time we run the program (see functions generate_mul_tbl (), generate_coef_tbl (), generate_LS_tbl ())

**Comment by pavel-collab** [comment]
@Exactlywb could you send me a link to some documentation to the source. I need to clearly understand the idea of this thee existing matrixes to make generation script and also for article. If you have no one, I will need more explanation.

**Comment by Exactlywb** [comment]
Lack of documentation is the feature of our project
